const ActionTypes = {
  SAVE_USER_DATA: 1,
  LOGOUT: 2,
  SAVE_SEARCH: 3,
  SAVE_SERVICES: 4,
  SAVE_SERVICES_DETAILS: 5,
  SAVE_USER_DATA_REGISTER: 6,
  SAVE_PRODUCT_DETALIS: 7,
  SAVE_HOSPITAL_DETALIS: 8,
  SAVE_REVIEWS: 9,
  SAVE_AVAILABILITIES: 10,
};
export default ActionTypes;
