export default {
  "Log in": "تسجيل الدخول",
  "Sign Up": "تسجيل جديد",
  "Forgot Password": "نسيت كلمة المرور",
  Profile: "الملف الشخصي",
  Save: "حفظ",
  "Log Out": "تسجل الخروج",
  Home: "الرئيسية",
  password: "كلمة المرور",
  "Phone number": "رقم الهاتف",
  Email: "البريد الإلكتروني",
  "First name": "الاسم الاول",
  "Last name": "الاسم الاخير",
  Send: "إرسال",
  Services: "خدمات",
  "Enaya for Doctors": "عناية للاطباء",
  Contact: "اتصال",
  "Best Doctors In Egypt": "افضل اطباء فى مصر",
  "Find the best doctors in Egypt, with easy search and Booking for you and for others in a simple way":
    "اعثر على أفضل الأطباء في مصر ، مع سهولة البحث والحجز لك وللآخرين بطريقة بسيطة",
  "Search privately to 34,456 doctors in all specialists":
    "ابحث بشكل خاص عن 34456 طبيبًا من جميع الأخصائيين",
  "Find doctor": "ابحث عن طبيب",
  "Enter doctor name, category, specialist…":
    "أدخل اسم الطبيب ، الفئة ، المتخصص ...",
  "Find what you are looking for": "جد ما تبحث عنه",
  "At Enaya we have more than 48390 Doctors in all specialties We want you to be sure that you are going to find the best doctors In easy and convenient way, Go ahead try Enaya today!":
    "لدينا في عناية أكثر من 48390 طبيبًا في جميع التخصصات ، ونريدك أن تتأكد من أنك ستعثر على أفضل الأطباء بطريقة سهلة ومريحة ، تفضل بتجربة عناية اليوم!",
  More: "أكثر",
  "The only app you’ll need": "التطبيق الوحيد الذي ستحتاجه",
  "Special Enaya Services": "خدمات عناية الخاصة",
  "Thousands of patients use Everyday to find the best doctors":
    "يستخدم آلاف المرضى كل يوم للعثور على أفضل الأطباء",
  "Join Enaya Today": "انضم إلى عناية اليوم",
  "Owned by Roaya Group for managing Hospitals":
    "مملوكة لمجموعة رؤيا لإدارة المستشفيات",
  "Meet Enaya": "تعرف على عناية",
  "About Us": "معلومات عنا",
  "Mobile App": "تطبيق الهاتف المحمول",
  "Enaya Care": "عناية كير",
  "Contact us": "اتصل بنا",
  "Terms Of Use": "تعليمات الاستخدام",
  "Privacy Policy": "سياسة خاصة",
  "Doctor Privacy Policy": "سياسة خصوصية الطبيب",
  Enaya: "عناية",
  "All Rights Reserved.Made by": "جميع الحقوق محفوظة",
  "Need Help?": "تحتاج مساعدة؟",
  Clinics: "عيادات",
  Hospitals: "المستشفيات",
  "Contact Enaya": "تواصل مع عناية",
  "We alway here to helps you": "نحن هنا دائما لمساعدتك",
  WantToGet:
    "ترغب في الحصول على اتصال؟ نحب أن نسمع منك. إليك كيف يمكنك الوصول إلينا",
  Address: "العناوين",
  Phone: "هاتف",
  "SEND US A MESSAGE": "أرسل لنا رسالة",
  "Get in touch with us": "ابق على تواصل معنا",
  "Enter Your Name *": "أدخل أسمك *",
  "Enter Your Phone *": "أدخل رقم هاتفك *",
  Subject: "موضوعات",
  "Your Meassge Here *": "قياساتك هنا *",
  "My Profile": "ملفي",
  "My Doctors": "أطبائي",
  "Enter your password": "ادخل رقمك السري",
  Male: "ذكر",
  Female: "أنثى",
  "Retype your password": "أعد كتابة كلمة المرور الخاصة بك",
  Book: "اطلب",
  Get: "حصول",
  "Find Services": "ابحث عن الخدمات",
};
